### ISSUE TITLE
Unclear how to create the evaluation engine jar file for the server

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/EvaluationEngine#9]
I tried exporting the Evaluation Engine to a jar (including all required libraries), but now I get xstream errors when trying to evaluate a run. What am I doing wrong?

```
[30-09-2018 00:49:42] [OK] [Process Run] Start processing run: 24360
com.thoughtworks.xstream.converters.ConversionException: name : name
---- Debugging information ----
message             : name
cause-exception     : java.lang.IllegalArgumentException
cause-message       : name
class               : org.openml.apiconnector.xml.Run
required-type       : org.openml.apiconnector.xml.Run
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
path                : /oml:run/oml:uploader_name
version             : not available
-------------------------------
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1185)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1169)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1040)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1031)
	at org.openml.apiconnector.io.HttpConnector.wrapHttpResponse(HttpConnector.java:116)
	at org.openml.apiconnector.io.HttpConnector.doApiRequest(HttpConnector.java:85)
        ...

Caused by: java.lang.IllegalArgumentException: name
	at sun.misc.URLClassPath$Loader.getResource(URLClassPath.java:729)
	at sun.misc.URLClassPath.getResource(URLClassPath.java:239)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:365)
        ...

{"error":"name : name
---- Debugging information ----
message             : name
cause-exception     : java.lang.IllegalArgumentException
cause-message       : name
class               : org.openml.apiconnector.xml.Run
required-type       : org.openml.apiconnector.xml.Run
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
path                : /oml:run/oml:uploader_name
version             : not available
-------------------------------"}
```

**Comment by joaquinvanschoren** [comment]
I managed to fix it by removing all non-Maven dependencies from the class path.
